name: XCS234_Default
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - notebook=6.4.5
  - tk>=8.6.8
  - matplotlib=3.4.3
  - numpy
  - pandas=1.3.4
  - tensorboard=2.7.0
  - pyyaml=6.0
  - pip=22.1.2
  - pip:
    - gym==0.24.1
    - pygame==2.1.2
