name: XCS234_Default
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - notebook=6.4.5
  - tk>=8.6.8
  - pandas=1.3.4
  - tensorboard=2.10.1
  - pyyaml=6.0
  - pip=22.1.2
  - pip:
    - matplotlib==3.5.2
    - numpy==1.23.1
    - gym==0.26.2
    - pygame==2.1.2
